version: '3'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./data:/app/data  # Pour les données persistantes
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`app.jonathanlore.fr`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.services.app.loadbalancer.server.port=8080"
    networks:
      - web

networks:
  web:
    external: true
